# Generated by Django 4.2.11 on 2026-03-24 04:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nfc_cards', '0002_card_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_drafts', to='nfc_cards.card')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['card', 'session_key'], name='nfc_cards_p_card_id_c4e8c7_idx')],
            },
        ),
    ]
