"""
Migration 0004: безопасные изменения схемы (LinkGroup + FK на Card).

Важно:
Ранее в этой миграции был RunPython, который удалял все Card/LinkGroup/PreviewDraft и сбрасывал sequences.
В production это недопустимо: миграции должны быть идемпотентными и не выполнять destructive операции.

Опасная очистка вынесена в management command: `python manage.py purge_cards --force [--reset-sequences]`.
"""

# Generated by Django 4.2.11 on 2026-03-30 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfc_cards', '0003_preview_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='link_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='nfc_cards.linkgroup'),
        ),
    ]
