# Generated by Django 4.2.11 on 2026-03-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc_cards', '0004_linkgroup_and_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='view_password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
